apiVersion: apps/v1

kind: Deployment
metadata:
  name: archivarius-deployment

spec:
  selector:
    matchLabels:
      app: archivarius

  template:
    metadata:
      labels:
        app: archivarius

    spec:
      containers:
        - name: archivarius
          image: rg.pl-waw.scw.cloud/namespace-anfanik/archivarius:stable
          imagePullPolicy: Always

          env:
            - name: POSTGRES_USER
              value: anfanik-archivarius
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: archivarius-secret
                  key: postgresPassword
            - name: POSTGRES_URL
              value: jdbc:postgresql://postgres-svc/anfanik-archivarius

      imagePullSecrets:
        - name: anfanik-container-registry

---

apiVersion: v1

kind: Service
metadata:
  name: archivarius-svc

spec:
  type: ClusterIP
  selector:
    app: archivarius
  ports:
    - port: 80
      targetPort: 8080

---

apiVersion: traefik.io/v1alpha1

kind: IngressRoute
metadata:
  name: archivarius-ingress
  labels:
    app: archivarius

spec:
  entryPoints:
    - web
  routes:
    - match: Host(`archivarius.anfanik.me`) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: archivarius-svc
          port: 80